import type { Recipe, MealPlan, GroceryStore, IngredientEntry } from './types'

// ---- Sample Grocery Stores ----
export const SAMPLE_STORES: GroceryStore[] = [
  {
    id: 'store_trader_joes',
    name: "Trader Joe's",
    address: '401 Bay St, San Francisco, CA 94133',
    phone: '(415) 351-1013',
    hours: [
      'Mon: 8:00 AM - 9:00 PM',
      'Tue: 8:00 AM - 9:00 PM',
      'Wed: 8:00 AM - 9:00 PM',
      'Thu: 8:00 AM - 9:00 PM',
      'Fri: 8:00 AM - 9:00 PM',
      'Sat: 8:00 AM - 9:00 PM',
      'Sun: 8:00 AM - 9:00 PM',
    ],
    createdAt: '2026-02-01T00:00:00Z',
    updatedAt: '2026-02-01T00:00:00Z',
  },
  {
    id: 'store_whole_foods',
    name: 'Whole Foods Market',
    address: '399 4th St, San Francisco, CA 94107',
    phone: '(415) 618-0066',
    hours: [
      'Mon: 7:00 AM - 10:00 PM',
      'Tue: 7:00 AM - 10:00 PM',
      'Wed: 7:00 AM - 10:00 PM',
      'Thu: 7:00 AM - 10:00 PM',
      'Fri: 7:00 AM - 10:00 PM',
      'Sat: 7:00 AM - 10:00 PM',
      'Sun: 7:00 AM - 10:00 PM',
    ],
    createdAt: '2026-02-01T00:00:00Z',
    updatedAt: '2026-02-01T00:00:00Z',
  },
  {
    id: 'store_safeway',
    name: 'Safeway',
    address: '2020 Market St, San Francisco, CA 94114',
    phone: '(415) 861-7660',
    hours: [
      'Mon: 6:00 AM - 11:00 PM',
      'Tue: 6:00 AM - 11:00 PM',
      'Wed: 6:00 AM - 11:00 PM',
      'Thu: 6:00 AM - 11:00 PM',
      'Fri: 6:00 AM - 11:00 PM',
      'Sat: 6:00 AM - 11:00 PM',
      'Sun: 6:00 AM - 11:00 PM',
    ],
    createdAt: '2026-02-01T00:00:00Z',
    updatedAt: '2026-02-01T00:00:00Z',
  },
]

// ---- Sample Ingredient Entries (the "database") ----
export const SAMPLE_INGREDIENT_ENTRIES: IngredientEntry[] = [
  // Produce
  { id: 'ie_avocado', name: 'ripe avocado', defaultUnit: '', defaultStoreId: 'store_safeway', category: 'Produce', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_romaine', name: 'romaine lettuce', defaultUnit: 'head', defaultStoreId: 'store_safeway', category: 'Produce', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_cucumber', name: 'cucumber', defaultUnit: '', defaultStoreId: 'store_safeway', category: 'Produce', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_red_bell_pepper', name: 'red bell pepper', defaultUnit: '', defaultStoreId: 'store_safeway', category: 'Produce', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_bell_peppers', name: 'bell peppers', defaultUnit: '', defaultStoreId: 'store_safeway', category: 'Produce', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_baby_spinach', name: 'baby spinach', defaultUnit: 'handful', defaultStoreId: 'store_whole_foods', category: 'Produce', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_broccoli', name: 'broccoli florets', defaultUnit: 'cup', defaultStoreId: 'store_safeway', category: 'Produce', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_snap_peas', name: 'snap peas', defaultUnit: 'cup', defaultStoreId: 'store_whole_foods', category: 'Produce', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_carrots', name: 'carrots', defaultUnit: '', defaultStoreId: 'store_safeway', category: 'Produce', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_celery', name: 'celery stalks', defaultUnit: '', defaultStoreId: 'store_safeway', category: 'Produce', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_yellow_onion', name: 'yellow onion', defaultUnit: '', defaultStoreId: 'store_safeway', category: 'Produce', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_garlic', name: 'garlic', defaultUnit: 'clove', defaultStoreId: 'store_safeway', category: 'Produce', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_green_onions', name: 'green onions', defaultUnit: '', defaultStoreId: 'store_safeway', category: 'Produce', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_fresh_ginger', name: 'fresh ginger', defaultUnit: 'tsp', defaultStoreId: 'store_whole_foods', category: 'Produce', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_lemon_juice', name: 'lemon juice', defaultUnit: 'tsp', defaultStoreId: 'store_safeway', category: 'Produce', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_blueberries', name: 'fresh blueberries', defaultUnit: 'cup', defaultStoreId: 'store_whole_foods', category: 'Produce', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_strawberries', name: 'fresh strawberries', defaultUnit: 'cup', defaultStoreId: 'store_whole_foods', category: 'Produce', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_mixed_berries', name: 'mixed berries', defaultUnit: 'cup', defaultStoreId: 'store_whole_foods', category: 'Produce', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },

  // Dairy & Eggs
  { id: 'ie_greek_yogurt', name: 'Greek yogurt', defaultUnit: 'cup', defaultStoreId: 'store_whole_foods', category: 'Dairy', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_almond_milk', name: 'almond milk', defaultUnit: 'cup', defaultStoreId: 'store_trader_joes', category: 'Dairy', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_large_eggs', name: 'large eggs', defaultUnit: '', defaultStoreId: 'store_safeway', category: 'Dairy', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_parmesan', name: 'parmesan cheese', defaultUnit: 'cup', defaultStoreId: 'store_whole_foods', category: 'Dairy', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_feta', name: 'feta cheese', defaultUnit: 'tbsp', defaultStoreId: 'store_whole_foods', category: 'Dairy', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },

  // Meat & Seafood
  { id: 'ie_chicken_breast', name: 'chicken breast', defaultUnit: '', defaultStoreId: 'store_safeway', category: 'Meat', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_ground_beef', name: 'ground beef', defaultUnit: 'lb', defaultStoreId: 'store_safeway', category: 'Meat', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_salmon', name: 'salmon fillets', defaultUnit: '', defaultStoreId: 'store_whole_foods', category: 'Meat', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_turkey', name: 'sliced turkey breast', defaultUnit: 'oz', defaultStoreId: 'store_safeway', category: 'Meat', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_tofu', name: 'extra-firm tofu', defaultUnit: 'oz', defaultStoreId: 'store_whole_foods', category: 'Meat', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },

  // Pantry
  { id: 'ie_rolled_oats', name: 'rolled oats', defaultUnit: 'cup', defaultStoreId: 'store_trader_joes', category: 'Pantry', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_chia_seeds', name: 'chia seeds', defaultUnit: 'tbsp', defaultStoreId: 'store_trader_joes', category: 'Pantry', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_honey', name: 'honey', defaultUnit: 'tbsp', defaultStoreId: 'store_whole_foods', category: 'Pantry', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_vanilla', name: 'vanilla extract', defaultUnit: 'tsp', defaultStoreId: 'store_trader_joes', category: 'Pantry', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_olive_oil', name: 'olive oil', defaultUnit: 'tbsp', defaultStoreId: 'store_trader_joes', category: 'Pantry', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_soy_sauce', name: 'soy sauce', defaultUnit: 'tbsp', defaultStoreId: 'store_trader_joes', category: 'Pantry', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_mirin', name: 'mirin', defaultUnit: 'tbsp', defaultStoreId: 'store_trader_joes', category: 'Pantry', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_sesame_oil', name: 'sesame oil', defaultUnit: 'tsp', defaultStoreId: 'store_trader_joes', category: 'Pantry', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_sesame_seeds', name: 'sesame seeds', defaultUnit: 'tsp', defaultStoreId: 'store_trader_joes', category: 'Pantry', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_rice_vinegar', name: 'rice vinegar', defaultUnit: 'tbsp', defaultStoreId: 'store_trader_joes', category: 'Pantry', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_dijon', name: 'Dijon mustard', defaultUnit: 'tsp', defaultStoreId: 'store_whole_foods', category: 'Pantry', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_worcestershire', name: 'Worcestershire sauce', defaultUnit: 'tsp', defaultStoreId: 'store_safeway', category: 'Pantry', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_anchovy_paste', name: 'anchovy paste', defaultUnit: 'tsp', defaultStoreId: 'store_whole_foods', category: 'Pantry', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_brown_sugar', name: 'brown sugar', defaultUnit: 'tbsp', defaultStoreId: 'store_safeway', category: 'Pantry', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_cornstarch', name: 'cornstarch', defaultUnit: 'tsp', defaultStoreId: 'store_safeway', category: 'Pantry', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_peanut_butter', name: 'peanut butter', defaultUnit: 'cup', defaultStoreId: 'store_trader_joes', category: 'Pantry', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_chocolate_chips', name: 'mini chocolate chips', defaultUnit: 'cup', defaultStoreId: 'store_safeway', category: 'Pantry', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_flaxseed', name: 'ground flaxseed', defaultUnit: 'tbsp', defaultStoreId: 'store_whole_foods', category: 'Pantry', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_granola', name: 'granola', defaultUnit: 'cup', defaultStoreId: 'store_trader_joes', category: 'Pantry', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_sliced_almonds', name: 'sliced almonds', defaultUnit: 'tbsp', defaultStoreId: 'store_trader_joes', category: 'Pantry', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_crushed_tomatoes', name: 'crushed tomatoes', defaultUnit: 'can', defaultStoreId: 'store_trader_joes', category: 'Pantry', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_tomato_paste', name: 'tomato paste', defaultUnit: 'tbsp', defaultStoreId: 'store_trader_joes', category: 'Pantry', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_red_wine', name: 'red wine', defaultUnit: 'cup', defaultStoreId: 'store_whole_foods', category: 'Pantry', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_hummus', name: 'hummus', defaultUnit: 'tbsp', defaultStoreId: 'store_trader_joes', category: 'Pantry', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },

  // Grains & Bread
  { id: 'ie_sourdough', name: 'sourdough bread', defaultUnit: 'slice', defaultStoreId: 'store_whole_foods', category: 'Bakery', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_flour_tortilla', name: 'large flour tortilla', defaultUnit: '', defaultStoreId: 'store_safeway', category: 'Bakery', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_spaghetti', name: 'spaghetti', defaultUnit: 'lb', defaultStoreId: 'store_trader_joes', category: 'Pantry', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_jasmine_rice', name: 'jasmine rice', defaultUnit: 'cup', defaultStoreId: 'store_trader_joes', category: 'Pantry', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_brown_rice', name: 'brown rice', defaultUnit: 'cup', defaultStoreId: 'store_trader_joes', category: 'Pantry', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_croutons', name: 'croutons', defaultUnit: 'cup', defaultStoreId: 'store_trader_joes', category: 'Bakery', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },

  // Spices
  { id: 'ie_red_pepper_flakes', name: 'red pepper flakes', defaultUnit: 'tsp', defaultStoreId: 'store_trader_joes', category: 'Spices', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_oregano', name: 'dried oregano', defaultUnit: 'tsp', defaultStoreId: 'store_trader_joes', category: 'Spices', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_bay_leaves', name: 'bay leaves', defaultUnit: '', defaultStoreId: 'store_trader_joes', category: 'Spices', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_salt', name: 'salt', defaultUnit: '', defaultStoreId: '', category: 'Spices', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
  { id: 'ie_black_pepper', name: 'black pepper', defaultUnit: '', defaultStoreId: '', category: 'Spices', createdAt: '2026-02-01T00:00:00Z', updatedAt: '2026-02-01T00:00:00Z' },
]

// ---- Helper to get store name by ID ----
function storeName(id: string): string {
  const found = SAMPLE_STORES.find((s) => s.id === id)
  return found?.name ?? ''
}

// ---- Sample Recipes ----
export const SAMPLE_RECIPES: Recipe[] = [
  {
    id: 'recipe_overnight_oats',
    name: 'Overnight Oats with Berries',
    description: 'Creamy overnight oats layered with fresh berries and a drizzle of honey. Perfect for busy mornings.',
    mealType: 'breakfast',
    servings: 2,
    ingredients: [
      { id: 'ing_1', name: 'rolled oats', qty: 1, unit: 'cup', store: storeName('store_trader_joes'), storeId: 'store_trader_joes' },
      { id: 'ing_2', name: 'almond milk', qty: 1, unit: 'cup', store: storeName('store_trader_joes'), storeId: 'store_trader_joes' },
      { id: 'ing_3', name: 'Greek yogurt', qty: 0.5, unit: 'cup', store: storeName('store_whole_foods'), storeId: 'store_whole_foods' },
      { id: 'ing_4', name: 'chia seeds', qty: 1, unit: 'tbsp', store: storeName('store_trader_joes'), storeId: 'store_trader_joes' },
      { id: 'ing_5', name: 'honey', qty: 2, unit: 'tbsp', store: storeName('store_whole_foods'), storeId: 'store_whole_foods' },
      { id: 'ing_6', name: 'fresh blueberries', qty: 0.5, unit: 'cup', store: storeName('store_whole_foods'), storeId: 'store_whole_foods' },
      { id: 'ing_7', name: 'fresh strawberries', qty: 0.5, unit: 'cup', store: storeName('store_whole_foods'), storeId: 'store_whole_foods' },
      { id: 'ing_8', name: 'vanilla extract', qty: 0.5, unit: 'tsp', store: storeName('store_trader_joes'), storeId: 'store_trader_joes' },
    ],
    steps: [
      'Combine oats, almond milk, yogurt, chia seeds, honey, and vanilla in a jar.',
      'Stir well, cover, and refrigerate overnight (at least 6 hours).',
      'In the morning, top with fresh blueberries and strawberries.',
      'Drizzle with extra honey if desired and serve cold.',
    ],
    sourceUrl: '',
    createdAt: '2026-02-10T08:00:00Z',
    updatedAt: '2026-02-10T08:00:00Z',
  },
  {
    id: 'recipe_avocado_toast',
    name: 'Avocado Toast with Poached Egg',
    description: 'Crispy sourdough topped with smashed avocado and a perfectly poached egg.',
    mealType: 'breakfast',
    servings: 1,
    ingredients: [
      { id: 'ing_9', name: 'sourdough bread', qty: 2, unit: 'slice', store: storeName('store_whole_foods'), storeId: 'store_whole_foods' },
      { id: 'ing_10', name: 'ripe avocado', qty: 1, unit: '', store: storeName('store_safeway'), storeId: 'store_safeway' },
      { id: 'ing_11', name: 'large eggs', qty: 2, unit: '', store: storeName('store_safeway'), storeId: 'store_safeway' },
      { id: 'ing_12', name: 'lemon juice', qty: 1, unit: 'tsp', store: storeName('store_safeway'), storeId: 'store_safeway' },
      { id: 'ing_13', name: 'red pepper flakes', qty: 0.25, unit: 'tsp', store: storeName('store_trader_joes'), storeId: 'store_trader_joes' },
      { id: 'ing_14', name: 'salt', qty: null, unit: '', store: '' },
      { id: 'ing_15', name: 'black pepper', qty: null, unit: '', store: '' },
    ],
    steps: [
      'Toast the sourdough slices until golden and crispy.',
      'Halve the avocado, remove the pit, and smash the flesh with a fork. Mix in lemon juice and a pinch of salt.',
      'Bring a pot of water to a gentle simmer. Add a splash of vinegar. Swirl the water and gently drop in the eggs. Poach for 3 minutes.',
      'Spread avocado onto toast, top with poached eggs, and sprinkle with red pepper flakes and pepper.',
    ],
    sourceUrl: '',
    createdAt: '2026-02-10T09:00:00Z',
    updatedAt: '2026-02-10T09:00:00Z',
  },
  {
    id: 'recipe_chicken_caesar',
    name: 'Grilled Chicken Caesar Salad',
    description: 'Classic caesar salad with grilled chicken breast, crunchy croutons, and homemade dressing.',
    mealType: 'lunch',
    servings: 2,
    ingredients: [
      { id: 'ing_16', name: 'chicken breast', qty: 2, unit: '', store: storeName('store_safeway'), storeId: 'store_safeway' },
      { id: 'ing_17', name: 'romaine lettuce', qty: 1, unit: 'head', store: storeName('store_safeway'), storeId: 'store_safeway' },
      { id: 'ing_18', name: 'parmesan cheese', qty: 0.5, unit: 'cup', store: storeName('store_whole_foods'), storeId: 'store_whole_foods' },
      { id: 'ing_19', name: 'croutons', qty: 1, unit: 'cup', store: storeName('store_trader_joes'), storeId: 'store_trader_joes' },
      { id: 'ing_20', name: 'olive oil', qty: 2, unit: 'tbsp', store: storeName('store_trader_joes'), storeId: 'store_trader_joes' },
      { id: 'ing_21', name: 'lemon juice', qty: 2, unit: 'tbsp', store: storeName('store_safeway'), storeId: 'store_safeway' },
      { id: 'ing_22', name: 'garlic', qty: 2, unit: 'clove', store: storeName('store_safeway'), storeId: 'store_safeway' },
      { id: 'ing_23', name: 'Dijon mustard', qty: 1, unit: 'tsp', store: storeName('store_whole_foods'), storeId: 'store_whole_foods' },
      { id: 'ing_24', name: 'Worcestershire sauce', qty: 1, unit: 'tsp', store: storeName('store_safeway'), storeId: 'store_safeway' },
      { id: 'ing_25', name: 'anchovy paste', qty: 1, unit: 'tsp', store: storeName('store_whole_foods'), storeId: 'store_whole_foods' },
    ],
    steps: [
      'Season chicken breasts with salt, pepper, and a drizzle of olive oil. Grill over medium-high heat for 6-7 minutes per side until cooked through. Let rest, then slice.',
      'Make the dressing: whisk together olive oil, lemon juice, minced garlic, Dijon mustard, Worcestershire sauce, and anchovy paste.',
      'Chop the romaine, toss with dressing, and top with sliced chicken, shaved parmesan, and croutons.',
    ],
    sourceUrl: '',
    createdAt: '2026-02-10T10:00:00Z',
    updatedAt: '2026-02-10T10:00:00Z',
  },
  {
    id: 'recipe_turkey_wrap',
    name: 'Turkey and Hummus Wrap',
    description: 'Quick and satisfying wrap with turkey, hummus, crunchy veggies, and feta.',
    mealType: 'lunch',
    servings: 1,
    ingredients: [
      { id: 'ing_26', name: 'large flour tortilla', qty: 1, unit: '', store: storeName('store_safeway'), storeId: 'store_safeway' },
      { id: 'ing_27', name: 'sliced turkey breast', qty: 4, unit: 'oz', store: storeName('store_safeway'), storeId: 'store_safeway' },
      { id: 'ing_28', name: 'hummus', qty: 3, unit: 'tbsp', store: storeName('store_trader_joes'), storeId: 'store_trader_joes' },
      { id: 'ing_29', name: 'cucumber', qty: 0.5, unit: '', store: storeName('store_safeway'), storeId: 'store_safeway' },
      { id: 'ing_30', name: 'red bell pepper', qty: 0.5, unit: '', store: storeName('store_safeway'), storeId: 'store_safeway' },
      { id: 'ing_31', name: 'baby spinach', qty: 1, unit: 'handful', store: storeName('store_whole_foods'), storeId: 'store_whole_foods' },
      { id: 'ing_32', name: 'feta cheese', qty: 2, unit: 'tbsp', store: storeName('store_whole_foods'), storeId: 'store_whole_foods' },
    ],
    steps: [
      'Spread hummus evenly over the tortilla.',
      'Layer turkey slices, sliced cucumber, bell pepper strips, spinach, and crumbled feta.',
      'Roll up tightly, tucking in the sides. Slice in half diagonally and serve.',
    ],
    sourceUrl: '',
    createdAt: '2026-02-10T11:00:00Z',
    updatedAt: '2026-02-10T11:00:00Z',
  },
  {
    id: 'recipe_salmon_teriyaki',
    name: 'Teriyaki Salmon with Steamed Rice',
    description: 'Pan-seared salmon glazed with a sweet and savory teriyaki sauce, served over fluffy rice.',
    mealType: 'dinner',
    servings: 2,
    ingredients: [
      { id: 'ing_33', name: 'salmon fillets', qty: 2, unit: '', store: storeName('store_whole_foods'), storeId: 'store_whole_foods' },
      { id: 'ing_34', name: 'soy sauce', qty: 3, unit: 'tbsp', store: storeName('store_trader_joes'), storeId: 'store_trader_joes' },
      { id: 'ing_35', name: 'mirin', qty: 2, unit: 'tbsp', store: storeName('store_trader_joes'), storeId: 'store_trader_joes' },
      { id: 'ing_36', name: 'brown sugar', qty: 1, unit: 'tbsp', store: storeName('store_safeway'), storeId: 'store_safeway' },
      { id: 'ing_37', name: 'fresh ginger', qty: 1, unit: 'tsp', store: storeName('store_whole_foods'), storeId: 'store_whole_foods' },
      { id: 'ing_38', name: 'garlic', qty: 2, unit: 'clove', store: storeName('store_safeway'), storeId: 'store_safeway' },
      { id: 'ing_39', name: 'jasmine rice', qty: 1, unit: 'cup', store: storeName('store_trader_joes'), storeId: 'store_trader_joes' },
      { id: 'ing_40', name: 'sesame seeds', qty: 1, unit: 'tsp', store: storeName('store_trader_joes'), storeId: 'store_trader_joes' },
      { id: 'ing_41', name: 'green onions', qty: 2, unit: '', store: storeName('store_safeway'), storeId: 'store_safeway' },
      { id: 'ing_42', name: 'sesame oil', qty: 1, unit: 'tsp', store: storeName('store_trader_joes'), storeId: 'store_trader_joes' },
    ],
    steps: [
      'Cook jasmine rice according to package directions.',
      'Mix soy sauce, mirin, brown sugar, minced ginger, and minced garlic in a small bowl.',
      'Pat salmon fillets dry and season with salt. Sear skin-side down in a hot pan with sesame oil for 4 minutes.',
      'Flip, pour sauce into the pan, and cook 3-4 more minutes, basting the salmon.',
      'Serve salmon over rice, drizzle with remaining sauce, and garnish with sesame seeds and sliced green onions.',
    ],
    sourceUrl: '',
    createdAt: '2026-02-11T08:00:00Z',
    updatedAt: '2026-02-11T08:00:00Z',
  },
  {
    id: 'recipe_pasta_bolognese',
    name: 'Classic Pasta Bolognese',
    description: 'Rich and hearty slow-simmered meat sauce tossed with al dente spaghetti.',
    mealType: 'dinner',
    servings: 4,
    ingredients: [
      { id: 'ing_43', name: 'spaghetti', qty: 1, unit: 'lb', store: storeName('store_trader_joes'), storeId: 'store_trader_joes' },
      { id: 'ing_44', name: 'ground beef', qty: 1, unit: 'lb', store: storeName('store_safeway'), storeId: 'store_safeway' },
      { id: 'ing_45', name: 'yellow onion', qty: 1, unit: '', store: storeName('store_safeway'), storeId: 'store_safeway' },
      { id: 'ing_46', name: 'garlic', qty: 4, unit: 'clove', store: storeName('store_safeway'), storeId: 'store_safeway' },
      { id: 'ing_47', name: 'crushed tomatoes', qty: 1, unit: 'can', store: storeName('store_trader_joes'), storeId: 'store_trader_joes' },
      { id: 'ing_48', name: 'tomato paste', qty: 2, unit: 'tbsp', store: storeName('store_trader_joes'), storeId: 'store_trader_joes' },
      { id: 'ing_49', name: 'carrots', qty: 2, unit: '', store: storeName('store_safeway'), storeId: 'store_safeway' },
      { id: 'ing_50', name: 'celery stalks', qty: 2, unit: '', store: storeName('store_safeway'), storeId: 'store_safeway' },
      { id: 'ing_51', name: 'red wine', qty: 0.5, unit: 'cup', store: storeName('store_whole_foods'), storeId: 'store_whole_foods' },
      { id: 'ing_52', name: 'olive oil', qty: 2, unit: 'tbsp', store: storeName('store_trader_joes'), storeId: 'store_trader_joes' },
      { id: 'ing_53', name: 'dried oregano', qty: 1, unit: 'tsp', store: storeName('store_trader_joes'), storeId: 'store_trader_joes' },
      { id: 'ing_54', name: 'bay leaves', qty: 2, unit: '', store: storeName('store_trader_joes'), storeId: 'store_trader_joes' },
      { id: 'ing_55', name: 'parmesan cheese', qty: 0.25, unit: 'cup', store: storeName('store_whole_foods'), storeId: 'store_whole_foods' },
    ],
    steps: [
      'Finely dice onion, carrots, and celery. Mince garlic.',
      'Heat olive oil in a large pot. Brown the ground beef, breaking it up. Remove and set aside.',
      'In the same pot, cook the onion, carrots, and celery for 5 minutes until softened. Add garlic and cook 1 minute.',
      'Pour in the red wine and scrape up browned bits. Cook until reduced by half.',
      'Add crushed tomatoes, tomato paste, oregano, bay leaves, and the beef back in. Simmer for 30-45 minutes.',
      'Cook spaghetti al dente according to package directions. Toss with sauce, remove bay leaves, and serve topped with parmesan.',
    ],
    sourceUrl: '',
    createdAt: '2026-02-11T09:00:00Z',
    updatedAt: '2026-02-11T09:00:00Z',
  },
  {
    id: 'recipe_veggie_stir_fry',
    name: 'Vegetable Stir-Fry with Tofu',
    description: 'Crispy tofu and colorful vegetables in a savory ginger-garlic sauce.',
    mealType: 'dinner',
    servings: 3,
    ingredients: [
      { id: 'ing_56', name: 'extra-firm tofu', qty: 14, unit: 'oz', store: storeName('store_whole_foods'), storeId: 'store_whole_foods' },
      { id: 'ing_57', name: 'broccoli florets', qty: 2, unit: 'cup', store: storeName('store_safeway'), storeId: 'store_safeway' },
      { id: 'ing_58', name: 'bell peppers', qty: 2, unit: '', store: storeName('store_safeway'), storeId: 'store_safeway' },
      { id: 'ing_59', name: 'snap peas', qty: 1, unit: 'cup', store: storeName('store_whole_foods'), storeId: 'store_whole_foods' },
      { id: 'ing_60', name: 'soy sauce', qty: 3, unit: 'tbsp', store: storeName('store_trader_joes'), storeId: 'store_trader_joes' },
      { id: 'ing_61', name: 'rice vinegar', qty: 1, unit: 'tbsp', store: storeName('store_trader_joes'), storeId: 'store_trader_joes' },
      { id: 'ing_62', name: 'cornstarch', qty: 1, unit: 'tsp', store: storeName('store_safeway'), storeId: 'store_safeway' },
      { id: 'ing_63', name: 'fresh ginger', qty: 1, unit: 'tbsp', store: storeName('store_whole_foods'), storeId: 'store_whole_foods' },
      { id: 'ing_64', name: 'garlic', qty: 3, unit: 'clove', store: storeName('store_safeway'), storeId: 'store_safeway' },
      { id: 'ing_65', name: 'vegetable oil', qty: 2, unit: 'tbsp', store: storeName('store_safeway'), storeId: 'store_safeway' },
      { id: 'ing_66', name: 'brown rice', qty: 1.5, unit: 'cup', store: storeName('store_trader_joes'), storeId: 'store_trader_joes' },
    ],
    steps: [
      'Press tofu for 15 minutes, then cut into cubes. Toss with cornstarch.',
      'Cook brown rice according to package directions.',
      'Heat oil in a wok over high heat. Fry tofu cubes until golden on all sides, about 5 minutes. Remove and set aside.',
      'Stir-fry broccoli, peppers, and snap peas for 3-4 minutes until tender-crisp.',
      'Add ginger and garlic, cook 30 seconds. Add soy sauce and rice vinegar. Return tofu to the wok and toss.',
      'Serve over brown rice.',
    ],
    sourceUrl: '',
    createdAt: '2026-02-12T08:00:00Z',
    updatedAt: '2026-02-12T08:00:00Z',
  },
  {
    id: 'recipe_fruit_yogurt',
    name: 'Greek Yogurt Fruit Parfait',
    description: 'Layers of creamy Greek yogurt, crunchy granola, and fresh seasonal fruit.',
    mealType: 'snack',
    servings: 1,
    ingredients: [
      { id: 'ing_67', name: 'Greek yogurt', qty: 1, unit: 'cup', store: storeName('store_whole_foods'), storeId: 'store_whole_foods' },
      { id: 'ing_68', name: 'granola', qty: 0.25, unit: 'cup', store: storeName('store_trader_joes'), storeId: 'store_trader_joes' },
      { id: 'ing_69', name: 'mixed berries', qty: 0.5, unit: 'cup', store: storeName('store_whole_foods'), storeId: 'store_whole_foods' },
      { id: 'ing_70', name: 'honey', qty: 1, unit: 'tsp', store: storeName('store_whole_foods'), storeId: 'store_whole_foods' },
      { id: 'ing_71', name: 'sliced almonds', qty: 1, unit: 'tbsp', store: storeName('store_trader_joes'), storeId: 'store_trader_joes' },
    ],
    steps: [
      'Spoon half the yogurt into a glass or bowl.',
      'Layer with half the granola and berries.',
      'Repeat with remaining yogurt, granola, and berries.',
      'Top with sliced almonds and a drizzle of honey.',
    ],
    sourceUrl: '',
    createdAt: '2026-02-12T09:00:00Z',
    updatedAt: '2026-02-12T09:00:00Z',
  },
  {
    id: 'recipe_energy_bites',
    name: 'No-Bake Energy Bites',
    description: 'Quick, protein-packed bites with oats, peanut butter, and chocolate chips.',
    mealType: 'snack',
    servings: 12,
    ingredients: [
      { id: 'ing_72', name: 'rolled oats', qty: 1, unit: 'cup', store: storeName('store_trader_joes'), storeId: 'store_trader_joes' },
      { id: 'ing_73', name: 'peanut butter', qty: 0.5, unit: 'cup', store: storeName('store_trader_joes'), storeId: 'store_trader_joes' },
      { id: 'ing_74', name: 'honey', qty: 0.333, unit: 'cup', store: storeName('store_whole_foods'), storeId: 'store_whole_foods' },
      { id: 'ing_75', name: 'mini chocolate chips', qty: 0.5, unit: 'cup', store: storeName('store_safeway'), storeId: 'store_safeway' },
      { id: 'ing_76', name: 'ground flaxseed', qty: 2, unit: 'tbsp', store: storeName('store_whole_foods'), storeId: 'store_whole_foods' },
      { id: 'ing_77', name: 'vanilla extract', qty: 1, unit: 'tsp', store: storeName('store_trader_joes'), storeId: 'store_trader_joes' },
    ],
    steps: [
      'Combine all ingredients in a large bowl and mix until well combined.',
      'Refrigerate for 30 minutes to make the mixture easier to handle.',
      'Roll into 1-inch balls and place on a parchment-lined tray.',
      'Store in the refrigerator in an airtight container for up to a week.',
    ],
    sourceUrl: '',
    createdAt: '2026-02-12T10:00:00Z',
    updatedAt: '2026-02-12T10:00:00Z',
  },
]

export const SAMPLE_MEAL_PLAN: MealPlan = {
  monday: {
    breakfast: 'recipe_overnight_oats',
    lunch: 'recipe_chicken_caesar',
    dinner: 'recipe_salmon_teriyaki',
    snack: 'recipe_fruit_yogurt',
  },
  tuesday: {
    breakfast: 'recipe_avocado_toast',
    lunch: 'recipe_turkey_wrap',
    dinner: 'recipe_pasta_bolognese',
    snack: 'recipe_energy_bites',
  },
  wednesday: {
    breakfast: 'recipe_overnight_oats',
    lunch: 'recipe_chicken_caesar',
    dinner: 'recipe_veggie_stir_fry',
    snack: null,
  },
  thursday: {
    breakfast: 'recipe_avocado_toast',
    lunch: null,
    dinner: 'recipe_salmon_teriyaki',
    snack: 'recipe_fruit_yogurt',
  },
  friday: {
    breakfast: null,
    lunch: 'recipe_turkey_wrap',
    dinner: 'recipe_pasta_bolognese',
    snack: 'recipe_energy_bites',
  },
  saturday: {
    breakfast: 'recipe_avocado_toast',
    lunch: null,
    dinner: 'recipe_veggie_stir_fry',
    snack: null,
  },
  sunday: {
    breakfast: 'recipe_overnight_oats',
    lunch: 'recipe_chicken_caesar',
    dinner: null,
    snack: null,
  },
}
